version: '2'

services:
  repository-miner-api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "4040:4040"
    env_file:
      - .env
    environment:
      - MONGO_HOST=mongodb://mongo/repository-miner-api-development
      - DEBUG=repository-miner-api:*
    links:
      - mongo
  mongo:
    image: "mongo:3.4.2"
    ports:
      - "27017:27017"
